services:
  rabbitmq:
    image: rabbitmq:3.12.9-management
    container_name: rabbit_container
    hostname: rabbit_server
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "123"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped
