apiVersion: apps/v1
kind: Deployment
metadata:
  name: machines-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machines
  template:
    metadata:
      labels:
        app: machines
    spec:
      containers:
        - name: machines-container
          image: machines-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8097

          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "machines"
            - name: DB_USER
              value: "estg"
            - name: DB_PASSWORD
              value: "estg"
            - name: RABBIT_HOST
              value: "rabbitmq-service"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"

