apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning
  template:
    metadata:
      labels:
        app: planning
    spec:
      containers:
        - name: planning-container
          image: planning-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8095

          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "planning"
            - name: DB_USER
              value: "estg"
            - name: DB_PASSWORD
              value: "estg"
            - name: RABBIT_HOST
              value: "rabbitmq-service"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: MACHINES_URL
              value: "http://machines"

