apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products-container
          image: products-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8092

          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "products"
            - name: DB_USER
              value: "estg"
            - name: DB_PASSWORD
              value: "estg"
            - name: RABBIT_HOST
              value: "rabbitmq-service"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
