apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels: {app: orders}
  template:
    metadata:
      labels: {app: orders}
    spec:
      containers:
        - name: orders-container
          image: orders-service:v1
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/orders"
            - name: SPRING_DATASOURCE_USERNAME
              value: "estg"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "estg"
            - name: RABBIT_HOST
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: CUSTOMERS_URL
              value: "http://customers"
            - name: INVENTORY_URL
              value: "http://inventory"
          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: 8080}
            initialDelaySeconds: 60
          readinessProbe:
            httpGet: {path: /actuator/health/readiness, port: 8080}
            initialDelaySeconds: 60