apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers-container
          image: customers-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "customers"
            - name: DB_USER
              value: "estg"
            - name: DB_PASSWORD
              value: "estg"
            - name: RABBIT_HOST
              value: "rabbitmq-service"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"

          ##livenessProbe:
            ##httpGet:
              ##path: /actuator/health/liveness
              ##port: 8080
            ##initialDelaySeconds: 30
            ##periodSeconds: 10
            ##failureThreshold: 3
          ##readinessProbe:
            ##httpGet:
              ##path: /actuator/health/readiness
              ##port: 8080
            ##initialDelaySeconds: 20
            ##periodSeconds: 5
            ##failureThreshold: 3